# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       maui-theme

# >> macros
# << macros

Summary:    Maui theme
Version:    0.3.90
Release:    1
Group:      Applications/System
License:    GPLv2+ and CC-BY-SA
BuildArch:  noarch
URL:        https://github.com/mauios/maui-theme.git
Source0:    %{name}-%{version}.tar.xz
Source100:  maui-theme.yaml
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  extra-cmake-modules
BuildRequires:  kde5-rpm-macros
BuildRequires:  qt5-tools
BuildRequires:  kf5-plasma-devel
BuildRequires:  hawaii-framework-devel

%description
Provides Maui theme for different programs.

%package -n maui-syslinux-splash
Summary:    Maui splash screen for boot loaders
Group:      System/Base

%description -n maui-syslinux-splash
This package contains Maui splash screen for boot loaders.


%package -n plymouth-theme-maui
Summary:    Plymouth "Maui" theme
Group:      System/Base
Requires:   plymouth-plugin-two-step

%description -n plymouth-theme-maui
This package contains the "Maui" theme for Plymouth.


%package -n grub-theme-maui
Summary:    Grub "Maui" theme
Group:      System/Base

%description -n grub-theme-maui
This package contains the "Maui" theme for grub.


%package -n maui-icon-theme
Summary:    Maui icon theme
Group:      System/Base
Requires:   kde5-breeze-icon-theme

%description -n maui-icon-theme
This package contains the "Maui" icon theme.


%package -n maui-cursor-theme
Summary:    Maui cursor theme
Group:      System/Base
Requires:   kde5-filesystem

%description -n maui-cursor-theme
This package contains the "Maui" cursor theme.


%package -n maui-wallpapers
Summary:    Maui wallpapers
Group:      System/Base
Requires:   kde5-filesystem

%description -n maui-wallpapers
This package contains wallpapers from the "Maui" visual style.


%package -n maui-plasma-theme
Summary:    Plasma "Maui" theme
Group:      System/Base
Requires:   kde5-filesystem

%description -n maui-plasma-theme
This package contains the "Maui" theme for Plasma.


%package -n qt5-qtquickcontrols-maui-style
Summary:    QtQuick Controls "Maui" style
Group:      System/Base
Requires:   qt5-qtquickcontrols
Requires:   hawaii-framework

%description -n qt5-qtquickcontrols-maui-style
This package contains the "Maui" style for QtQuick Controls.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# << install post


%files -n maui-syslinux-splash
%defattr(-,root,root,-)
%{_datadir}/pixmaps/syslinux-splash.png
# >> files maui-syslinux-splash
# << files maui-syslinux-splash

%files -n plymouth-theme-maui
%defattr(-,root,root,-)
%dir %{_datadir}/plymouth/themes/maui
%{_datadir}/plymouth/themes/maui/*.png
%{_datadir}/plymouth/themes/maui/maui.plymouth
# >> files plymouth-theme-maui
# << files plymouth-theme-maui

%files -n grub-theme-maui
%defattr(-,root,root,-)
/boot/grub/themes/maui
# >> files grub-theme-maui
# << files grub-theme-maui

%files -n maui-icon-theme
%defattr(-,root,root,-)
%{_kde5_datadir}/icons/maui/*
%exclude %{_kde5_datadir}/icons/maui/cursors
# >> files maui-icon-theme
# << files maui-icon-theme

%files -n maui-cursor-theme
%defattr(-,root,root,-)
%{_kde5_datadir}/icons/maui/cursors
# >> files maui-cursor-theme
# << files maui-cursor-theme

%files -n maui-wallpapers
%defattr(-,root,root,-)
%{_kde5_datadir}/wallpapers/*
# >> files maui-wallpapers
# << files maui-wallpapers

%files -n maui-plasma-theme
%defattr(-,root,root,-)
%{_kde5_datadir}/plasma/desktoptheme/maui/
# >> files maui-plasma-theme
# << files maui-plasma-theme

%files -n qt5-qtquickcontrols-maui-style
%defattr(-,root,root,-)
%doc COPYING AUTHORS
%{_kde5_libdir}/qml/QtQuick/Controls/Styles/Maui/*
# >> files qt5-qtquickcontrols-maui-style
# << files qt5-qtquickcontrols-maui-style
