# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       maui-theme

# >> macros
# << macros

Summary:    Maui theme
Version:    0.2.90
Release:    1
Group:      Applications/System
License:    GPLv2+ and CC-BY-SA
BuildArch:  noarch
URL:        https://github.com/mauios/maui-theme.git
Source0:    %{name}-%{version}.tar.xz
Source100:  maui-theme.yaml
BuildRequires:  cmake

%description
Provides Maui theme for different programs.

%package -n maui-syslinux-splash
Summary:    Maui splash screen for boot loaders
Group:      System/Base

%description -n maui-syslinux-splash
This package contains Maui splash screen for boot loaders.


%package -n plymouth-theme-maui
Summary:    Plymouth "Maui" theme
Group:      System/Base

%description -n plymouth-theme-maui
This package contains the "Maui" theme for Plymouth.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake . 
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files -n maui-syslinux-splash
%defattr(-,root,root,-)
%{_datadir}/pixmaps/syslinux-splash.png
# >> files maui-syslinux-splash
# << files maui-syslinux-splash

%files -n plymouth-theme-maui
%defattr(-,root,root,-)
%{_datadir}/plymouth/themes/maui
# >> files plymouth-theme-maui
# << files plymouth-theme-maui
